### ISSUE TITLE
Derive password for selected Label when pressing Enter

### ISSUE THREAD

**Issue by PanosSakkos** [dono-app/dono-macos#18]

**Comment by tanishgupta16** [comment]
Can you explain the issue more clearly?

**Comment by PanosSakkos** [comment]
Hi @tanishgupta16 ,

Sure. When you click on a Label, then it will be selected (and hilighted with a gray color).
Then if you hit the return key, then the LabelsViewController.tableViewDoubleClick function should be called, and the rest will be taken care off 😉 

Is clear now?

**Comment by funky-monkey** [comment]
I'm picking this up for #hacktoberfest
